name: Auth CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker image to ECR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_URI }}:latest ./services/auth-service

      - name: Tag image
        run: |
          docker tag ${{ secrets.ECR_REPO_URI }}:latest ${{ secrets.ECR_REPO_URI }}:latest

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URI }}:latest
